### ISSUE TITLE
1.2.18 and newer: "TypeError: _this.connect is not a function at Object.Realtime"

### ISSUE THREAD

**Issue by tander29** [ably/ably-js#970]
Using ably.RealTime and getting this issue on connecting, 1.2.18, 1.2.19, and 1.2.20 all seem to have this behavior

1.2.17 and early seem to work.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1820) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @tander29 thanks for reporting this. Could you give us a bit more info about how to reproduce this error and which platform you're running ably-js on?

**Comment by owenpearson** [comment]
I'm pretty sure the issue here is that you're calling the `Realtime` constructor without the `new` keyword. This worked in ably-js previously but in 1.2.18 and above you need to use the `new` keyword.

**Comment by tander29** [comment]
@owenpearson Genius!  That seems to be working, thanks for the quick reply
