### ISSUE TITLE
Many callbacks are potentially invoked with an error that doesn't conform to public API

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1405]
There are a couple of issues here:

- Many of our public methods which are meant to emit an `ErrorInfo` (as [defined by our type definitions](https://github.com/ably/ably-js/blob/92003d88d89f5d165748396944cc51bc5d00863f/ably.d.ts#L733-L746)) do not do so (at least, according to static type information — whether this actually is occurring at runtime I don't know) — they only emit an [`IPartialErrorInfo`](https://github.com/ably/ably-js/blob/92003d88d89f5d165748396944cc51bc5d00863f/src/common/lib/types/errorinfo.ts#L5-L10) (and before this type was introduced in 2395b88a1e9dc16965a5f9753429a889f72a7da3 they were instead emitting an `ErrorInfo` class, however that class did not actually conform to the public `ErrorInfo` interface).
- This issue is not being caught by the compiler, because the implementations of these methods are referring to [these internally-defined](https://github.com/ably/ably-js/blob/92003d88d89f5d165748396944cc51bc5d00863f/src/common/types/utils.d.ts#L1-L3) callback types, which refer to an "`ErrorInfo`" type that they do not in fact import. The result of this is that (for reasons I don't understand), instead of causing a compilation failure as one might expect, references to this `ErrorInfo` type just seem to be ignored by the compiler. If you add `import ErrorInfo from '../lib/types/errorinfo';` to the top of `src/common/types/utils.d.ts` you'll see that a whole bunch of compilation errors related to the previous bullet point suddenly appear.

So, we should probably:

1. Fix the fact that this issue is not causing a compilation error. My suggestion would be that we remove the callback types defined in `src/common/types/utils.d.ts` and instead directly refer to the callback types defined in the public `ably.d.ts` interface. (In fact, I’d go further and say that we should also be making sure that all of our types which are intended to implement an interface defined in `ably.d.ts` should explicitly declare that they implement this interface. That is, for example, the [`Auth` class](https://github.com/ably/ably-js/blob/main/src/common/lib/client/auth.ts) should declare `implements API.Types.Auth` etc.)

   And then, once the compilation errors appear, temporarily suppress them with type assertions until we do the next step.
2. Make sure that all of the public methods that are meant to emit an `ErrorInfo` do in fact so do. This is the tricker step and requires us to figure out how to work around the fact, as described in 2395b88a1e9dc16965a5f9753429a889f72a7da3, that:

   > we are internally using an `ErrorInfo` with `code === null` to communicate something (?) which then gets picked up by `auth.ts`’s `normaliseAuthcallbackError` function.
